(function(){
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const VERSION='1.0.3'; let active=null, rec=null, stream=null, timer=null, busy=false, lang={locked:null,candidate:null,score:0};
const store=()=>{try{return JSON.parse(localStorage.loggNotes||'[]')}catch{return[]}};
const saveStore=x=>localStorage.loggNotes=JSON.stringify(x);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=ms=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(ms));
function view(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.body.dataset.view=id;scrollTo(0,0)}
function slug(s){return (s||'Note').replace(/[^a-z0-9åäö_-]+/gi,'_').replace(/^_+|_+$/g,'').slice(0,70)||'Note'}
function fresh(){active={id:String(Date.now()),title:'',created:Date.now(),updated:Date.now(),body:''}; lang={locked:null,candidate:null,score:0}; loadEditor();view('notes');setTimeout(()=>$('#noteTitle')?.focus(),120)}
function loadEditor(){if(!active)return;$('#noteTitle').value=active.title||'';$('#noteBody').value=active.body||'';$('#noteStamp').textContent=fmt(active.created);voiceState('Ready · Smart auto SV/FI/EN/ES')}
function persist(silent=true){if(!active)return;active.title=$('#noteTitle').value.trim();active.body=$('#noteBody').value;active.updated=Date.now();if(!active.title&&!active.body.trim())return;let x=store(),i=x.findIndex(n=>n.id===active.id);if(i>=0)x[i]=active;else x.push(active);saveStore(x);if(!silent&&window.toast)toast('Saved')}
function list(){let x=store().slice().sort((a,b)=>b.updated-a.updated),el=$('#notesList');el.innerHTML=x.length?x.map(n=>`<div class="recent-item note-item" data-id="${n.id}"><div><div class="recent-title">${esc(n.title||'Untitled note')}</div><div class="recent-meta">${fmt(n.updated)} · ${esc((n.body||'').replace(/^[•☐\-]\s*/gm,'').slice(0,72))}</div></div><div>›</div></div>`).join(''):'<div class="empty">No notes yet.</div>';$$('.note-item').forEach(e=>e.onclick=()=>{active=store().find(n=>n.id===e.dataset.id);loadEditor();view('notes')})}
function insertPrefix(prefix){let a=$('#noteBody'),start=a.selectionStart,end=a.selectionEnd,val=a.value,before=val.slice(0,start),sel=val.slice(start,end)||'',after=val.slice(end);let atLine=start===0||before.endsWith('\n');let ins=(atLine?'':'\n')+prefix+(sel||'');a.value=before+ins+after;a.focus();a.selectionStart=a.selectionEnd=before.length+ins.length;persist()}
function continueListOnEnter(e){
  if(e.key!=='Enter'||e.shiftKey||e.altKey||e.ctrlKey||e.metaKey)return;
  const a=e.currentTarget,start=a.selectionStart,end=a.selectionEnd;
  if(start!==end)return;
  const before=a.value.slice(0,start), line=before.slice(before.lastIndexOf('\n')+1);
  const m=line.match(/^(\s*)(• |☐ |☑ |- )/);
  if(!m)return;
  e.preventDefault();
  // Empty list item: Enter once exits the list instead of creating endless blank bullets.
  if(line.slice(m[0].length).trim()===''){
    const lineStart=before.lastIndexOf('\n')+1;
    a.value=a.value.slice(0,lineStart)+a.value.slice(start);
    a.selectionStart=a.selectionEnd=lineStart;
  }else{
    const prefix=m[1]+(m[2]==='☑ '?'☐ ':m[2]);
    a.setRangeText('\n'+prefix,start,end,'end');
  }
  persist();
}
function voiceState(s){let e=$('#noteVoiceState');if(e)e.textContent=s}
function norm(code=''){code=String(code).toLowerCase();if(code.startsWith('sv'))return'sv-SE';if(code.startsWith('en'))return'en-GB';if(code.startsWith('fi'))return'fi-FI';if(code.startsWith('es'))return'es-ES';return null}
function observe(codes=[]){if(lang.locked)return;let l=norm(codes[0]);if(!l)return;if(lang.candidate===l)lang.score+=(l==='sv-SE'?2:1);else{lang.candidate=l;lang.score=l==='sv-SE'?2:1}if(lang.score>=3)lang.locked=l}
function appendSpeech(text){text=String(text||'').trim();if(!text)return;let parts=text.split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);let a=$('#noteBody'),prefix=a.value.trim()?'\n':'';a.value+=prefix+parts.map(s=>'• '+s).join('\n');a.scrollTop=a.scrollHeight;persist()}
async function transcribe(blob,type){if(busy||blob.size<800)return;busy=true;voiceState('Transcribing…');try{let ext=type.includes('mp4')?'m4a':type.includes('webm')?'webm':'audio',fd=new FormData();fd.append('audio',blob,'note.'+ext);if(lang.locked)fd.append('languageHint',lang.locked);let base=(window.LOGG_CONFIG?.API_BASE||'').replace(/\/$/,'');let r=await fetch(base+'/api/transcribe',{method:'POST',body:fd});if(!r.ok)throw Error(await r.text());let j=await r.json();observe(j.detectedLanguages||[]);appendSpeech(j.transcript);voiceState('Listening · '+(lang.locked?'LOCK '+lang.locked:'Smart auto SV/FI/EN/ES'))}catch(e){voiceState('Speech error · tap to retry');console.error(e)}finally{busy=false}}
async function recordChunk(){if(!stream)return;let types=['audio/mp4','audio/webm;codecs=opus','audio/webm'],type=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'';let chunks=[];rec=new MediaRecorder(stream,type?{mimeType:type}:undefined);let actual=rec.mimeType||type||'audio/webm';rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onstop=()=>{if(chunks.length)transcribe(new Blob(chunks,{type:actual}),actual);if(stream)setTimeout(recordChunk,80)};rec.start(1000);timer=setTimeout(()=>{if(rec?.state==='recording'){try{rec.requestData()}catch{}setTimeout(()=>{if(rec?.state==='recording')rec.stop()},120)}},7000)}
async function startVoice(){try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$('#noteVoiceBtn').classList.add('recording');$('#noteVoiceBtn span').textContent='STOP';voiceState('Listening · Smart auto SV/FI/EN/ES');recordChunk()}catch(e){voiceState('Microphone permission required')}}
function stopVoice(){clearTimeout(timer);let s=stream;stream=null;if(rec?.state==='recording')try{rec.stop()}catch{}s?.getTracks().forEach(t=>t.stop());$('#noteVoiceBtn').classList.remove('recording');$('#noteVoiceBtn span').textContent='VOICE';voiceState('Ready · '+(lang.locked?'LOCK '+lang.locked:'Smart auto SV/FI/EN/ES'))}
function toggleVoice(){stream?stopVoice():startVoice()}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
const crcTable=(()=>{let t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();function crc32(a){let c=0xffffffff;for(let b of a)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function u16(n){return[n&255,n>>>8&255]}function u32(n){return[n&255,n>>>8&255,n>>>16&255,n>>>24&255]}function zip(files){let enc=new TextEncoder(),out=[],central=[],off=0;for(let[name,content]of files){let nb=enc.encode(name),data=enc.encode(content),crc=crc32(data),h=[0x50,0x4b,3,4,...u16(20),0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),0,0,...nb,...data];out.push(...h);central.push([nb,data,crc,off]);off+=h.length}let cs=off;for(let[nb,data,crc,lo]of central){let h=[0x50,0x4b,1,2,...u16(20),...u16(20),0,0,0,0,0,0,...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),0,0,0,0,0,0,0,0,...u32(lo),...nb];out.push(...h);off+=h.length}out.push(0x50,0x4b,5,6,0,0,0,0,...u16(central.length),...u16(central.length),...u32(off-cs),...u32(cs),0,0);return new Uint8Array(out)}
function xml(s){return String(s).replace(/[<>&\"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}function para(text,opt=''){let bold=opt==='title'||opt==='brand',size=opt==='brand'?34:opt==='title'?30:opt==='meta'?18:22,color=opt==='brand'?'8D734A':'1B1B18';return `<w:p><w:pPr><w:spacing w:after="${opt==='brand'?60:opt==='title'?180:80}"/></w:pPr><w:r><w:rPr>${bold?'<w:b/>':''}<w:color w:val="${color}"/><w:sz w:val="${size}"/><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/></w:rPr><w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>`}
function exportDocx(){persist();let body=para('LOGG','brand')+para('MEETINGS ON COURSE · NOTE','meta')+para(active.title||'Untitled note','title')+para(fmt(active.created),'meta')+para('────────────────────────────────','meta');for(let line of (active.body||'').split('\n'))body+=para(line||' ');let files=[['[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'],['_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],['word/document.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`]];download(new Blob([zip(files)],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),`LOGG_NOTE_${slug(active.title)}.docx`)}
function exportJson(){persist();download(new Blob([JSON.stringify({format:'LOGG Note',version:1,...active},null,2)],{type:'application/json'}),`LOGG_NOTE_${slug(active.title)}.json`)}
function exportPdf(){persist();let f=document.createElement('iframe');f.setAttribute('aria-hidden','true');f.style.cssText='position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none';document.body.appendChild(f);let d=f.contentDocument||f.contentWindow.document;d.open();d.write(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(active.title||'LOGG Note')}</title><style>@page{margin:22mm}body{font-family:Arial,sans-serif;color:#1b1b18;line-height:1.65}.brand{font-weight:800;letter-spacing:.16em;font-size:22px;color:#8d734a}.sub{font-size:9px;letter-spacing:.2em;color:#8d734a;margin:2px 0 34px}.meta{font-size:10px;color:#766f64;border-bottom:1px solid #cbb993;padding-bottom:14px}h1{font-size:28px;margin:8px 0}.body{white-space:pre-wrap;font-size:13px;margin-top:28px}</style><div class="brand">LOGG</div><div class="sub">MEETINGS ON COURSE · NOTE</div><h1>${esc(active.title||'Untitled note')}</h1><div class="meta">${esc(fmt(active.created))}</div><div class="body">${esc(active.body||'')}</div>`);d.close();setTimeout(()=>{try{f.contentWindow.focus();f.contentWindow.print()}catch(e){voiceState('PDF export unavailable in this browser')}setTimeout(()=>f.remove(),1500)},250)}
function closeExport(){const sh=$('#noteExportSheet');if(sh)sh.hidden=true}
function notesHome(){closeExport();stopVoice();persist();view('home')}
function installNotesSwipe(){
  let start=null;
  const bind=(sel,handler)=>{const el=$(sel);if(!el)return;
    el.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('button,input,select,textarea,a')){start=null;return}const t=e.touches[0];start={x:t.clientX,y:t.clientY,time:Date.now()}},{passive:true});
    el.addEventListener('touchend',e=>{if(!start)return;const t=e.changedTouches[0],q=start;start=null;if(!t)return;const dx=t.clientX-q.x,dy=t.clientY-q.y,dt=Date.now()-q.time;if(dx>=80&&Math.abs(dx)>Math.abs(dy)*1.35&&dt<1000)handler()},{passive:true});
  };
  bind('#notes .stationery',()=>{$('#noteExportSheet')?.hidden===false?closeExport():notesHome()});
  bind('#notesLibrary .stationery',()=>view('home'));
  bind('#noteExportSheet',closeExport);
}
function init(){document.documentElement.dataset.notesModule=VERSION;$('#openNotes').onclick=fresh;$('#backNotes').onclick=notesHome;$('#notesLibraryBtn').onclick=()=>{stopVoice();persist();list();view('notesLibrary')};$('#backNotesLibrary').onclick=()=>view('home');$('#newNoteBtn').onclick=fresh;$('#noteBulletBtn').onclick=()=>insertPrefix('• ');$('#noteCheckBtn').onclick=()=>insertPrefix('☐ ');$('#noteVoiceBtn').onclick=toggleVoice;$('#noteSaveBtn').onclick=()=>{persist(false);list()};$('#noteExportBtn').onclick=()=>{persist();$('#noteExportSheet').hidden=false};$('#noteExportCancel').onclick=closeExport;$('#noteExportClose').onclick=closeExport;$('#noteExportSheet').addEventListener('click',e=>{if(e.target.id==='noteExportSheet')closeExport()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeExport()});$$('[data-note-export]').forEach(b=>b.onclick=()=>{let k=b.dataset.noteExport;closeExport();requestAnimationFrame(()=>{k==='docx'?exportDocx():k==='json'?exportJson():exportPdf()})});let autosave=()=>persist();$('#noteTitle').addEventListener('input',autosave);$('#noteBody').addEventListener('input',autosave);$('#noteBody').addEventListener('keydown',continueListOnEnter);installNotesSwipe();}
LOGG.registerModule('notes',{version:VERSION,status:'active',capabilities:['voice','typed','bullets','checklist','export-docx','export-pdf','export-json'],init});
})();
